### PR TITLE
Setup sbt-ci-release 

### PR DESCRIPTION
**Pull request by alexarchambault**
This PR sets up [sbt-ci-release](https://github.com/olafurpg/sbt-ci-release), in order to publish fansi from Travis CI.

For this to work fine, the environment variables [described in the sbt-ci-release README](https://github.com/olafurpg/sbt-ci-release/#travis) need to be set up in the Travis settings of fansi. @lihaoyi Is it something you can add to the settings?

### CODE REVIEW

**Comment by alexarchambault** [comment]
(The `0.2.6` commit corresponds to the release I made a few weeks ago.)

**Comment by alexarchambault** [comment]
@lihaoyi Is it something you'd be fine with?

Tell us if there's any way we can help further (cc-ing @olafurpg)

**Comment by olafurpg** [comment]
@lihaoyi would you be open to grant me and @alexarchambault collaborator rights in this repo? We would like to publish fansi for 2.13 :)

**Comment by lihaoyi** [comment]
done

**Comment by alexarchambault** [comment]
Seems [it worked](https://travis-ci.org/lihaoyi/fansi/jobs/536186403). Going to tag `0.2.7` (as `v0.2.7`, with a `v` prefix for sbt-dynver that sbt-ci-release relies on).

**Comment by alexarchambault** [comment]
Or wait for scala `2.13.0-RC2` maybe.

**Pull request merged**
